TIER2_TO_DCP = {
    "age_at_PFT": "donor_organism.medical_tests.pft_age",
    "age_unit": "donor_organism.organism_age_unit.text",
    "age_value": "donor_organism.organism_age",
    "alcohol_status": "donor_organism.medical_history.alcohol_status",
    "alcohol_type": "donor_organism.medical_history.alcohol_type",
    "alcohol_units": "donor_organism.medical_history.alcohol_units",
    "alcohol_usage_duration": "donor_organism.medical_history.alcohol_usage_duration",
    "bmi": "donor_organism.human_specific.body_mass_index",
    "cause_of_death": "donor_organism.death.cause_of_death",
    "cell_suspension_storage_time": "cell_suspension.preservation_storage.storage_time",
    "cell_suspension_storage_time_unit": "cell_suspension.preservation_storage.storage_time_unit.text",
    "comorbidities": "donor_organism.comorbidities.text",
    "cat_score": "donor_organism.disease_profile.copd_cat_score",
    "donor_id": "donor_organism.biomaterial_core.biomaterial_id",
    "emphysema_percentage": "donor_organism.disease_profile.copd_emphysema_percentage",
    "ethnicity_parents_selfreported_freetext": "donor_organism.human_specific.ethnicity_parents.text",
    "gold_abe_assessment": "donor_organism.disease_profile.copd_gold_abe_assessment",
    "gold_stage": "donor_organism.disease_profile.copd_gold_stage",
    "mmrc_grade": "donor_organism.disease_profile.copd_mMRC_grade",
    "copd_phenotype": "donor_organism.disease_profile.copd_phenotype",
    "digestion_solution": "dissociation_protocol.digestion_solution",
    "digestion_temperature": "dissociation_protocol.digestion_temperature",
    "disease_free_text": "donor_organism.diseases.text",
    "diseases": "donor_organism.diseases.text",
    "dissociation_description": "dissociation_protocol.protocol_core.protocol_description",
    "dissociation_doi": "dissociation_protocol.protocol_core.protocols_io_doi",
    "dlco_percent_of_predicted": "donor_organism.medical_tests.dlco",
    "ethnicity_selfreported_freetext": "donor_organism.human_specific.ethnicity.text",
    "fev1_fvc_ratio_postbd": "donor_organism.medical_tests.fev1_fvc_ratio_postbd",
    "fev1_fvc_ratio_prebd": "donor_organism.medical_tests.fev1_fvc_ratio_prebd",
    "fev1_milliliters_postbd": "donor_organism.medical_tests.fev1_postbd",
    "fev1_milliliters_prebd": "donor_organism.medical_tests.fev1_prebd",
    "fev1_milliliters_predicted": "donor_organism.medical_tests.fev1_predicted",
    "fev1_percent_of_predicted_postbd": "donor_organism.medical_tests.fev1_postbd_predicted_percent",
    "fev1_percent_of_predicted_prebd": "donor_organism.medical_tests.fev1_prebd_predicted_percent",
    "frc_abs_milliliters": "donor_organism.medical_tests.frc_abs",
    "frc_percent_of_predicted": "donor_organism.medical_tests.frc_predicted_percent",
    "fvc_milliliters_postbd": "donor_organism.medical_tests.fvc_postbd",
    "fvc_milliliters_prebd": "donor_organism.medical_tests.fvc_prebd",
    "fvc_milliliters_predicted": "donor_organism.medical_tests.fvc_predicted",
    "fvc_percent_of_predicted_postbd": "donor_organism.medical_tests.fvc_postbd_predicted_percent",
    "fvc_percent_of_predicted_prebd": "donor_organism.medical_tests.fvc_prebd_predicted_percent",
    "genderidentity_selfreported": "donor_organism.gender_identity.text",
    "genotype": "donor_organism.biomaterial_core.genotype",
    "gross_description": "specimen_from_organism.state_of_specimen.gross_description",
    "height": "donor_organism.height",
    "kco_mmol_min_kpa_l": "donor_organism.medical_tests.kco",
    "library_id": "cell_suspension.biomaterial_core.biomaterial_id",
    "medical_test_results": "donor_organism.medical_history.test_results",
    "medications": "donor_organism.medical_history.medication.text",
    "organ_donation_death_type": "donor_organism.death.organ_donation_death_type",
    "pft_method": "donor_organism.medical_tests.pft_method",
    "pft_relative_time_point": "donor_organism.medical_tests.pft_relative_time_point",
    "pft_time_point": "donor_organism.medical_tests.pft_time_point",
    # "protocol_tissue_dissociation": "dissociation_protocol.digestion_",
    # "protocol_tissue_dissociation_free_text": "dissociation_protocol.digestion_",
    "rv_milliliters": "donor_organism.medical_tests.rv",
    "rv_percent_of_predicted": "donor_organism.medical_tests.rv_predicted_percent",
    "sample_id": "specimen_from_organism.biomaterial_core.biomaterial_id",
    "sex": "donor_organism.sex",
    "smoking_pack_years": "donor_organism.medical_history.smoking_pack_years",
    "smoking_status": "donor_organism.medical_history.smoking_status",
    "time_of_collection": "specimen_from_organism.collection_time",
    "time_of_death": "donor_organism.death.time_of_death",
    "treatments": "donor_organism.medical_history.treatment",
    "weight": "donor_organism.weight",
    "years_since_smoking_cessation": "donor_organism.medical_history.years_since_smoking_cessation",
}

TIER2_TO_DCP_UPDATE = {
    "age_at_pft": "donor_organism.medical_tests.age_at_pft",
    "comorbidities_ontology_term_id": "donor_organism.medical_history.comorbidities.ontology",
    "diet_meat_consumption": "donor_organism.medical_history.diet_meat_consumption",
    "dlco_milliliters": "donor_organism.medical_tests.dlco_milliliters",
    "ethnicity_question_text": "donor_organism.ethnicity.question_text",
    "fev1_fvc_ratio_postbd": "donor_organism.medical_tests.fev1_fvc_ratio_postbd",
    "fev1_fvc_ratio_prebd": "donor_organism.medical_tests.fev1_fvc_ratio_prebd",
    "fev1_milliliters_postbd": "donor_organism.medical_tests.fev1_postbd_milliliters",
    "fev1_milliliters_prebd": "donor_organism.medical_tests.fev1_prebd_milliliters",
    "fev1_percent_of_predicted_postbd": "donor_organism.medical_tests.fev1_postbd_predicted_percent",
    "fev1_percent_of_predicted_prebd": "donor_organism.medical_tests.fev1_prebd_predicted_percent",
    "fvc_milliliters_prebd": "donor_organism.medical_tests.fvc_prebd_milliliters",
    "fvc_percent_of_predicted_postbd": "donor_organism.medical_tests.fvc_postbd_predicted_percent",
    "fvc_percent_of_predicted_prebd": "donor_organism.medical_tests.fvc_prebd_predicted_percent",
    "geography_collectionsite_latitude_longitude": "donor_organism.human_specific.collection_site.latitude_longitude",
    "geography_currentresidence_duration": "donor_organism.human_specific.current_residence.duration",
    "geography_currentresidence_location_country_state": "donor_organism.human_specific.current_residence.location.country_state",
    "geography_currentresidence_location_granular": "donor_organism.human_specific.current_residence.location.granular",
    "geography_currentresidence_urbanrural": "donor_organism.human_specific.current_residence.urban_rural",
    "geography_placeofbirth_duration": "donor_organism.human_specific.place_of_birth.duration",
    "geography_placeofbirth_location_country_state": "donor_organism.human_specific.place_of_birth.location.country_state",
    "geography_placeofbirth_location_granular": "donor_organism.human_specific.place_of_birth.location.granular",
    "geography_placeofbirth_urbanrural": "donor_organism.human_specific.place_of_birth.urban_rural",
    "household_smoking_exposure": "donor_organism.medical_history.household_smoking_exposure",
    "vaping_status": "donor_organism.medical_history.vaping_status",
    "ic_milliliters": "donor_organism.medical_tests.ic_milliliters",
    "ic_percent_of_predicted": "donor_organism.medical_tests.ic_predicted_percent",
    "kco_percent_of_predicted": "donor_organism.medical_tests.kco_predicted_percent",
    "language_donor_primary_language": "donor_organism.language.primary_language",
    "language_mother_father_tongue": "donor_organism.language.mother_father_tongue",
    "marijuana_inhaled_status": "donor_organism.medical_history.marijuana_inhaled_status",
    "medication_within_last_month_pre_sample": "donor_organism.medical_history.medication.text",
    "menarche_age": "donor_organism.reproductive.menarche_age",
    "percentage_of_emphysema": "donor_organism.medical_tests.percentage_of_emphysema",
    "reproductive_menopause": "donor_organism.reproductive.menopause",
    "reproductive_number_children": "donor_organism.reproductive.number_of_children",
    "reproductive_number_pregnancies": "donor_organism.reproductive.number_of_pregnancies",
    "sample_collection_time_point": "specimen_from_organism.collection_time",
    "gold_abe_assessment": "donor_organism.medical_history.copd_gold_abe_assessment",
    "mmrc_grade": "donor_organism.disease_profile.copd_mmrc_grade",
    #gut 
    "disease_ontology_term": "donor_organism.diseases.text",
    "disease_ontology_term_id": "donor_organism.diseases.ontology",
    "known_gut_related_disease": "donor_organism.diseases.text",
    "disease_location": "donor_organism.disease_location",
    "macroscopic_appearance": "specimen_from_organism.state_of_specimen.gross_description",
    "radial_tissue_term": "donor_organism.radial_tissue",
    "procedure": "collection_protocol.procedure",
    "indication_for_sampling": "collection_protocol.indication",
    "diet_specific": "donor_organism.medical_history.diet_specific",
}

restrictions_tier2 = {
    "age_in_med_history": {
        "fields": ["age_at_PFT"],
        "restrictions": "less than 'age_value'",
    }
}


LUNG_DIGESTION = {
    "Collagenase D + DNAse": {
        # "dissociation_protocol.protocol_core.protocol_id": "Collagenase_D_DNAse",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Collagenase D||DNAse",
    },
    "Dispase + collagenase": {
        # "dissociation_protocol.protocol_core.protocol_id": "Dispase_collagenase",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Dispase||Collagenase",
    },
    "Cold protease 1h": {
        # "dissociation_protocol.protocol_core.protocol_id": "Cold_protease_1h",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Protease",
        "dissociation_protocol.digestion_temperature": "cold",
        "dissociation_protocol.digestion_time": 1,
        "dissociation_protocol.digestion_time_unit": "hour",
    },
    "Collagenase + Elastase + DNAse": {
        # "dissociation_protocol.protocol_core.protocol_id": "Collagenase_Elastase_DNAse",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Collagenase||Elastase||DNAse",
    },
    "Cold protease overnight": {
        # "dissociation_protocol.protocol_core.protocol_id": "Cold_protease_overnight",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Protease",
        "dissociation_protocol.digestion_temperature": "cold",
        "dissociation_protocol.digestion_time": 16,
        "dissociation_protocol.digestion_time_unit": "hour",
    },
    "Collagenase A + DNAse": {
        # "dissociation_protocol.protocol_core.protocol_id": "Collagenase_A_DNAse",
        "dissociation_protocol.method.text": "enzymatic dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129",
        "dissociation_protocol.method.ontology_label": "enzymatic dissociation",
        "dissociation_protocol.digestion_solution": "Collagenase A||DNAse",
    },
    "Mechanical dissociation (chilled) + detergent-based nuclei isolation": {
        # "dissociation_protocol.protocol_core.protocol_id": "Mechanical_dissociation_detergent-based_nuclei_isolation",
        "dissociation_protocol.method.text": "mechanical dissociation||enzyme-free chemical dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129||EFO:0011026",
        "dissociation_protocol.method.ontology_label": "mechanical dissociation||enzyme-free chemical dissociation",
        "dissociation_protocol.digestion_solution": "Detergent-based",
        "dissociation_protocol.digestion_temperature": 8,
    },
    "Mechanical dissociation (frozen) + citric-acid based nuclei isolation": {
        # "dissociation_protocol.protocol_core.protocol_id": "Mechanical_dissociation_citric-acid_based_nuclei_isolation",
        "dissociation_protocol.method.text": "mechanical dissociation||enzyme-free chemical dissociation",
        "dissociation_protocol.method.ontology": "EFO:0009129||EFO:0011026",
        "dissociation_protocol.method.ontology_label": "mechanical dissociation||enzyme-free chemical dissociation",
        "dissociation_protocol.digestion_solution": "Citric-acid based",
        "dissociation_protocol.digestion_temperature": "frozen",
    },
}

TIER2_MANUAL_FIX = {
    "tier2": ["protocol_tissue_dissociation", "protocol_tissue_dissociation_free_text"],
    "dcp": [
        # "dissociation_protocol.protocol_core.protocol_id",
        "dissociation_protocol.method.text",
        "dissociation_protocol.method.ontology",
        "dissociation_protocol.method.ontology_label",
        "dissociation_protocol.digestion_solution",
        "dissociation_protocol.digestion_temperature",
        "dissociation_protocol.digestion_time",
        "dissociation_protocol.digestion_time_unit",
    ],
}
